"""Migrate audience path to heavy binary blob

Revision ID: 58e6865b6299
Revises: be83912b14d1
Create Date: 2026-04-06 08:30:28.939166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e6865b6299'
down_revision: Union[str, None] = 'be83912b14d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('audience_file_name', sa.String(length=255), nullable=True))
    op.add_column('surveys', sa.Column('audience_file_content', sa.LargeBinary(), nullable=True))
    op.drop_column('surveys', 'audience_file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('audience_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('surveys', 'audience_file_content')
    op.drop_column('surveys', 'audience_file_name')
    # ### end Alembic commands ###
