"""Add audience_list to Survey

Revision ID: 9ce8f670f941
Revises: e14fc7327d4a
Create Date: 2026-04-06 07:45:13.019532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce8f670f941'
down_revision: Union[str, None] = 'e14fc7327d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('audience_list', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'audience_list')
    # ### end Alembic commands ###
