"""Change audience_list to audience_file_path

Revision ID: be83912b14d1
Revises: 9ce8f670f941
Create Date: 2026-04-06 08:26:11.018421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be83912b14d1'
down_revision: Union[str, None] = '9ce8f670f941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('audience_file_path', sa.String(length=500), nullable=True))
    op.drop_column('surveys', 'audience_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('audience_list', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('surveys', 'audience_file_path')
    # ### end Alembic commands ###
